global:
  customer: geta
  environment: production
  tenant: demo
  imageRegistry:
    pullSecrets:
      - name: test
    basePath: harbor.teamgeta.net/gcc/
  otel:
    enabled: true
    endpoint:
      host: otel.test.com
      credentials: 1234567890=
  infisical:
    hostAPI: https://infisical.gks.zone/api
    credentialsRef:
      secretName: infisical-auth-secret
      secretNamespace: infisical-secrets-operator

enabled: true
name: cms
provider: sanity

api:
  image:
    tag: v2.0.0

dapr:
  enabled: true
  configuration:
    enabled: true
  component:
    enabled: true
  resiliency:
    enabled: true

infisicalSecret:
  enabled: true
  name: cms-api-secrets
  projectSlug: gcc-g9-aw
  envSlug: test
  secretsPath: /services/test

tests:
  enabled: false